// Static reference metadata for all 114 Surahs of the Qur'an — number, name,
// Arabic heading, English meaning, verse count and Makki/Madani classification.
// This is fixed, universally-known Qur'anic reference data (not sourced from any
// single site) used to build the Surah index without a network round-trip.

export interface SurahMeta {
  number: number
  name: string
  arabicName: string
  englishMeaning: string
  versesCount: number
  revelationType: 'Makki' | 'Madani'
}

export const SURAHS: SurahMeta[] = [
  { number: 1, name: 'Al Fatihah', arabicName: 'اَلْفَاتِحَة', englishMeaning: 'The Opening', versesCount: 7, revelationType: 'Makki' },
  { number: 2, name: 'Al Baqarah', arabicName: 'اَلْبَقَرَة', englishMeaning: 'The Cow', versesCount: 286, revelationType: 'Madani' },
  { number: 3, name: 'Al Imran', arabicName: 'اٰلِ عِمْرَان', englishMeaning: 'The Family of Imran', versesCount: 200, revelationType: 'Madani' },
  { number: 4, name: 'An Nisa', arabicName: 'اَلنِّسَآء', englishMeaning: 'The Women', versesCount: 176, revelationType: 'Madani' },
  { number: 5, name: 'Al Maidah', arabicName: 'اَلْمَـآئِدَة', englishMeaning: 'The Table Spread', versesCount: 120, revelationType: 'Madani' },
  { number: 6, name: 'Al Anam', arabicName: 'اَلْاَ نْعَام', englishMeaning: 'The Cattle', versesCount: 165, revelationType: 'Makki' },
  { number: 7, name: 'Al Araf', arabicName: 'اَلْاَعْرَاف', englishMeaning: 'The Heights', versesCount: 206, revelationType: 'Makki' },
  { number: 8, name: 'Al Anfal', arabicName: 'اَلْاَ نْفَال', englishMeaning: 'The Spoils of War', versesCount: 75, revelationType: 'Madani' },
  { number: 9, name: 'At Taubah', arabicName: 'اَلتَّوْبَة', englishMeaning: 'The Repentance', versesCount: 129, revelationType: 'Madani' },
  { number: 10, name: 'Yunus', arabicName: 'يُوْنُس', englishMeaning: 'Jonah', versesCount: 109, revelationType: 'Makki' },
  { number: 11, name: 'Hud', arabicName: 'هُوْد', englishMeaning: 'Hud', versesCount: 123, revelationType: 'Makki' },
  { number: 12, name: 'Yusuf', arabicName: 'يُوْسُف', englishMeaning: 'Joseph', versesCount: 111, revelationType: 'Makki' },
  { number: 13, name: 'Ar Rad', arabicName: 'اَلرَّعْد', englishMeaning: 'The Thunder', versesCount: 43, revelationType: 'Madani' },
  { number: 14, name: 'Ibrahim', arabicName: 'اِبرٰهِيْم', englishMeaning: 'Abraham', versesCount: 52, revelationType: 'Makki' },
  { number: 15, name: 'Al Hijr', arabicName: 'اَلْحِجْر', englishMeaning: 'The Rocky Tract', versesCount: 99, revelationType: 'Makki' },
  { number: 16, name: 'An Nahl', arabicName: 'اَلنَّحْل', englishMeaning: 'The Bee', versesCount: 128, revelationType: 'Makki' },
  { number: 17, name: 'Al Isra', arabicName: 'بَنِیْٓ اِسْرَآءِیْل', englishMeaning: 'The Night Journey', versesCount: 111, revelationType: 'Makki' },
  { number: 18, name: 'Al Kahf', arabicName: 'اَلْـكَهْف', englishMeaning: 'The Cave', versesCount: 110, revelationType: 'Makki' },
  { number: 19, name: 'Maryam', arabicName: 'مَرْيَم', englishMeaning: 'Mary', versesCount: 98, revelationType: 'Makki' },
  { number: 20, name: 'Taha', arabicName: 'طٰهٰ', englishMeaning: 'Ta-Ha', versesCount: 135, revelationType: 'Makki' },
  { number: 21, name: 'Al anbya', arabicName: 'اَلْاَ نْبِيَآء', englishMeaning: 'The Prophets', versesCount: 112, revelationType: 'Makki' },
  { number: 22, name: 'Al Hajj', arabicName: 'اَلْحَجّ', englishMeaning: 'The Pilgrimage', versesCount: 78, revelationType: 'Madani' },
  { number: 23, name: 'Al Muminun', arabicName: 'اَلْمُؤْمِنُوْن', englishMeaning: 'The Believers', versesCount: 118, revelationType: 'Makki' },
  { number: 24, name: 'An Noor', arabicName: 'اَلنُّوْر', englishMeaning: 'The Light', versesCount: 64, revelationType: 'Madani' },
  { number: 25, name: 'Al Furqan', arabicName: 'اَلْفُرْقَان', englishMeaning: 'The Criterion', versesCount: 77, revelationType: 'Makki' },
  { number: 26, name: 'ash shuara', arabicName: 'اَلشُّـعَرَاء', englishMeaning: 'The Poets', versesCount: 227, revelationType: 'Makki' },
  { number: 27, name: 'An Naml', arabicName: 'اَلنَّمْل', englishMeaning: 'The Ants', versesCount: 93, revelationType: 'Makki' },
  { number: 28, name: 'Al Qasas', arabicName: 'اَلْقَصَص', englishMeaning: 'The Narration', versesCount: 88, revelationType: 'Makki' },
  { number: 29, name: 'Al Ankabut', arabicName: 'اَلْعَنْـكَبُوْت', englishMeaning: 'The Spider', versesCount: 69, revelationType: 'Makki' },
  { number: 30, name: 'Ar Rum', arabicName: 'اَلرُّوْم', englishMeaning: 'The Romans', versesCount: 60, revelationType: 'Makki' },
  { number: 31, name: 'Luqman', arabicName: 'لُقْمٰن', englishMeaning: 'Luqman', versesCount: 34, revelationType: 'Makki' },
  { number: 32, name: 'As Sajda', arabicName: 'اَلسَّجْدَة', englishMeaning: 'The Prostration', versesCount: 30, revelationType: 'Makki' },
  { number: 33, name: 'Al Ahzab', arabicName: 'اَلْاَحْزَاب', englishMeaning: 'The Combined Forces', versesCount: 73, revelationType: 'Madani' },
  { number: 34, name: 'Sabah', arabicName: 'سَبَا', englishMeaning: 'Sheba', versesCount: 54, revelationType: 'Makki' },
  { number: 35, name: 'Fatir', arabicName: 'اَلْفَاطِر', englishMeaning: 'The Originator', versesCount: 45, revelationType: 'Makki' },
  { number: 36, name: 'Yasin', arabicName: 'يـٰسٓ', englishMeaning: 'Ya-Sin', versesCount: 83, revelationType: 'Makki' },
  { number: 37, name: 'As Saffat', arabicName: 'اَلصّٰٓفّٰت', englishMeaning: 'Those Ranged in Ranks', versesCount: 182, revelationType: 'Makki' },
  { number: 38, name: 'Sad', arabicName: 'صٓ', englishMeaning: 'Sad', versesCount: 88, revelationType: 'Makki' },
  { number: 39, name: 'Az Zumar', arabicName: 'اَلزُّمَر', englishMeaning: 'The Troops', versesCount: 75, revelationType: 'Makki' },
  { number: 40, name: 'Al Momin', arabicName: 'اَلْمُؤْمِن', englishMeaning: 'The Forgiver', versesCount: 85, revelationType: 'Makki' },
  { number: 41, name: 'Fussilat', arabicName: 'حٰمٓ اَلسَّجْدَۃ', englishMeaning: 'Explained in Detail', versesCount: 54, revelationType: 'Makki' },
  { number: 42, name: 'Ash Shura', arabicName: 'اَلشُّوْرٰی', englishMeaning: 'The Consultation', versesCount: 53, revelationType: 'Makki' },
  { number: 43, name: 'Az Zukhruf', arabicName: 'اَلزُّخْرُف', englishMeaning: 'The Ornaments of Gold', versesCount: 89, revelationType: 'Makki' },
  { number: 44, name: 'Ad Dukhan', arabicName: 'اَلدُّخَان', englishMeaning: 'The Smoke', versesCount: 59, revelationType: 'Makki' },
  { number: 45, name: 'Al Jathiyah', arabicName: 'اَلْجَاثِيَة', englishMeaning: 'The Kneeling', versesCount: 37, revelationType: 'Makki' },
  { number: 46, name: 'Al Ahqaf', arabicName: 'اَلْاَحْقَاف', englishMeaning: 'The Wind-Curved Sandhills', versesCount: 35, revelationType: 'Makki' },
  { number: 47, name: 'Muhammad', arabicName: 'مُحَمَّد', englishMeaning: 'Muhammad', versesCount: 38, revelationType: 'Madani' },
  { number: 48, name: 'Al Fath', arabicName: 'اَلْفَتْح', englishMeaning: 'The Victory', versesCount: 29, revelationType: 'Madani' },
  { number: 49, name: 'Al Hujurat', arabicName: 'اَلْحُجُرٰت', englishMeaning: 'The Private Apartments', versesCount: 18, revelationType: 'Madani' },
  { number: 50, name: 'Qaf', arabicName: 'قٓ', englishMeaning: 'Qaf', versesCount: 45, revelationType: 'Makki' },
  { number: 51, name: 'Az Zariyat', arabicName: 'اَلذّٰرِيـٰت', englishMeaning: 'The Winnowing Winds', versesCount: 60, revelationType: 'Makki' },
  { number: 52, name: 'At Tur', arabicName: 'اَلطُّوْر', englishMeaning: 'The Mount', versesCount: 49, revelationType: 'Makki' },
  { number: 53, name: 'An Najm', arabicName: 'اَلنَّجْم', englishMeaning: 'The Star', versesCount: 62, revelationType: 'Makki' },
  { number: 54, name: 'Al Qamar', arabicName: 'اَلْقَمَر', englishMeaning: 'The Moon', versesCount: 55, revelationType: 'Makki' },
  { number: 55, name: 'Ar Rahman', arabicName: 'اَلرَّحْمٰن', englishMeaning: 'The Most Merciful', versesCount: 78, revelationType: 'Makki' },
  { number: 56, name: 'Al Waqiah', arabicName: 'اَلْوَاقِعَة', englishMeaning: 'The Inevitable', versesCount: 96, revelationType: 'Makki' },
  { number: 57, name: 'Hadid', arabicName: 'اَلْحَدِيْد', englishMeaning: 'The Iron', versesCount: 29, revelationType: 'Madani' },
  { number: 58, name: 'Al Mujadilah', arabicName: 'اَلْمُجَادَلَة', englishMeaning: 'The Pleading Woman', versesCount: 22, revelationType: 'Madani' },
  { number: 59, name: 'Al Hashr', arabicName: 'اَلْحَشْر', englishMeaning: 'The Exile', versesCount: 24, revelationType: 'Madani' },
  { number: 60, name: 'Al Mumtahanah', arabicName: 'اَلْمُمْتَحِنَة', englishMeaning: 'She That is to be Examined', versesCount: 13, revelationType: 'Madani' },
  { number: 61, name: 'As Saf', arabicName: 'اَلصَّفّ', englishMeaning: 'The Ranks', versesCount: 14, revelationType: 'Madani' },
  { number: 62, name: 'Al Jumuah', arabicName: 'اَلْجُمُعَة', englishMeaning: 'Friday', versesCount: 11, revelationType: 'Madani' },
  { number: 63, name: 'Al Munafiqun', arabicName: 'اَلْمُنٰفِقُوْن', englishMeaning: 'The Hypocrites', versesCount: 11, revelationType: 'Madani' },
  { number: 64, name: 'At Taghabun', arabicName: 'اَلتَّغَابُن', englishMeaning: 'Mutual Disillusion', versesCount: 18, revelationType: 'Madani' },
  { number: 65, name: 'At Talaq', arabicName: 'اَلطَّلَاق', englishMeaning: 'Divorce', versesCount: 12, revelationType: 'Madani' },
  { number: 66, name: 'At Tahrim', arabicName: 'اَلتَّحْرِيْم', englishMeaning: 'The Prohibition', versesCount: 12, revelationType: 'Madani' },
  { number: 67, name: 'Al Mulk', arabicName: 'اَلْمُلْك', englishMeaning: 'The Sovereignty', versesCount: 30, revelationType: 'Makki' },
  { number: 68, name: 'Al Qalam', arabicName: 'اَلْقَلَم', englishMeaning: 'The Pen', versesCount: 52, revelationType: 'Makki' },
  { number: 69, name: 'Al Haqqah', arabicName: 'اَلْحَآ قَّة', englishMeaning: 'The Reality', versesCount: 52, revelationType: 'Makki' },
  { number: 70, name: 'Al Maarij', arabicName: 'اَلْمَعَارِ ج', englishMeaning: 'The Ascending Stairways', versesCount: 44, revelationType: 'Makki' },
  { number: 71, name: 'Nuh', arabicName: 'نُوْ ح', englishMeaning: 'Noah', versesCount: 28, revelationType: 'Makki' },
  { number: 72, name: 'Al Jin', arabicName: 'اَلْجِنّ', englishMeaning: 'The Jinn', versesCount: 28, revelationType: 'Makki' },
  { number: 73, name: 'Al Muzzammil', arabicName: 'اَلْمُزَّمِّل', englishMeaning: 'The Enshrouded One', versesCount: 20, revelationType: 'Makki' },
  { number: 74, name: 'Al Mudassir', arabicName: 'اَلْمُدَّثِّر', englishMeaning: 'The Cloaked One', versesCount: 56, revelationType: 'Makki' },
  { number: 75, name: 'Al Qiyamah', arabicName: 'اَلْقِيَامَة', englishMeaning: 'The Resurrection', versesCount: 40, revelationType: 'Makki' },
  { number: 76, name: 'Al Insan', arabicName: 'اَلدَّهْر', englishMeaning: 'Man', versesCount: 31, revelationType: 'Madani' },
  { number: 77, name: 'Al Mursalat', arabicName: 'اَلْمُرْسَلٰت', englishMeaning: 'Those Sent Forth', versesCount: 50, revelationType: 'Makki' },
  { number: 78, name: 'An Naba', arabicName: 'اَلنَّبَا', englishMeaning: 'The Tidings', versesCount: 40, revelationType: 'Makki' },
  { number: 79, name: 'An Naziat', arabicName: 'اَلنَّازِعَات', englishMeaning: 'Those Who Drag Forth', versesCount: 46, revelationType: 'Makki' },
  { number: 80, name: 'Abasa', arabicName: 'عَبَس', englishMeaning: 'He Frowned', versesCount: 42, revelationType: 'Makki' },
  { number: 81, name: 'At Takwir', arabicName: 'اَلتَّكْوِيْر', englishMeaning: 'The Overthrowing', versesCount: 29, revelationType: 'Makki' },
  { number: 82, name: 'Al Infitar', arabicName: 'اَلْاِنْفِطَار', englishMeaning: 'The Cleaving', versesCount: 19, revelationType: 'Makki' },
  { number: 83, name: 'Al Mutaffifin', arabicName: 'اَلْمُطَفِّفِيْن', englishMeaning: 'The Defrauding', versesCount: 36, revelationType: 'Makki' },
  { number: 84, name: 'Al Inshiqaq', arabicName: 'اَلْاِنْشِقَاق', englishMeaning: 'The Splitting Open', versesCount: 25, revelationType: 'Makki' },
  { number: 85, name: 'Al Buruj', arabicName: 'اَلْبُرُوْج', englishMeaning: 'The Mansions of the Stars', versesCount: 22, revelationType: 'Makki' },
  { number: 86, name: 'At Tariq', arabicName: 'اَلطَّارِق', englishMeaning: 'The Nightcomer', versesCount: 17, revelationType: 'Makki' },
  { number: 87, name: 'Al Ala', arabicName: 'اَلْاَعْلٰی', englishMeaning: 'The Most High', versesCount: 19, revelationType: 'Makki' },
  { number: 88, name: 'Al Ghashiyah', arabicName: 'اَلْغَاشِيَة', englishMeaning: 'The Overwhelming', versesCount: 26, revelationType: 'Makki' },
  { number: 89, name: 'Al Fajr', arabicName: 'اَلْفَجْر', englishMeaning: 'The Dawn', versesCount: 30, revelationType: 'Makki' },
  { number: 90, name: 'Al Balad', arabicName: 'اَلْبَـلَد', englishMeaning: 'The City', versesCount: 20, revelationType: 'Makki' },
  { number: 91, name: 'Ash Shams', arabicName: 'اَلشَّمْس', englishMeaning: 'The Sun', versesCount: 15, revelationType: 'Makki' },
  { number: 92, name: 'Al Lail', arabicName: 'اَلَّيْل', englishMeaning: 'The Night', versesCount: 21, revelationType: 'Makki' },
  { number: 93, name: 'Ad Duha', arabicName: 'اَلْضُّحٰی', englishMeaning: 'The Morning Hours', versesCount: 11, revelationType: 'Makki' },
  { number: 94, name: 'Alam Nashrah', arabicName: 'اَلَمْ نَشْرَ ح', englishMeaning: 'The Relief', versesCount: 8, revelationType: 'Makki' },
  { number: 95, name: 'At Tin', arabicName: 'اَلتِّیْن', englishMeaning: 'The Fig', versesCount: 8, revelationType: 'Makki' },
  { number: 96, name: 'Al Alaq', arabicName: 'اَلْعَلَق', englishMeaning: 'The Clot', versesCount: 19, revelationType: 'Makki' },
  { number: 97, name: 'Al Qadr', arabicName: 'اَلْقَدَر', englishMeaning: 'The Night of Decree', versesCount: 5, revelationType: 'Makki' },
  { number: 98, name: 'Al Baiyinah', arabicName: 'اَلْبَيِّنَة', englishMeaning: 'The Clear Proof', versesCount: 8, revelationType: 'Madani' },
  { number: 99, name: 'Az Zilzal', arabicName: 'اَلزِّلْزَال', englishMeaning: 'The Earthquake', versesCount: 8, revelationType: 'Madani' },
  { number: 100, name: 'Al Adiyat', arabicName: 'اَلْعٰدِيٰت', englishMeaning: 'The Courser', versesCount: 11, revelationType: 'Makki' },
  { number: 101, name: 'Al Qariah', arabicName: 'اَلْقَارِعَة', englishMeaning: 'The Calamity', versesCount: 11, revelationType: 'Makki' },
  { number: 102, name: 'At Takasur', arabicName: 'اَلتَّكَاثُر', englishMeaning: 'The Rivalry in World Increase', versesCount: 8, revelationType: 'Makki' },
  { number: 103, name: 'Al Asr', arabicName: 'اَلْعَصْر', englishMeaning: 'The Declining Day', versesCount: 3, revelationType: 'Makki' },
  { number: 104, name: 'Al Humazah', arabicName: 'اَلْهُمَزَة', englishMeaning: 'The Traducer', versesCount: 9, revelationType: 'Makki' },
  { number: 105, name: 'Al Fil', arabicName: 'اَلْفِيْل', englishMeaning: 'The Elephant', versesCount: 5, revelationType: 'Makki' },
  { number: 106, name: 'Quraish', arabicName: 'قُـرَيْش', englishMeaning: 'Quraysh', versesCount: 4, revelationType: 'Makki' },
  { number: 107, name: 'Al Maun', arabicName: 'اَلْمَاعُوْن', englishMeaning: 'Small Kindnesses', versesCount: 7, revelationType: 'Makki' },
  { number: 108, name: 'Al Kausar', arabicName: 'اَلْـكَوْثَر', englishMeaning: 'Abundance', versesCount: 3, revelationType: 'Makki' },
  { number: 109, name: 'Al Kafirun', arabicName: 'اَلْكَافِرُوْن', englishMeaning: 'The Disbelievers', versesCount: 6, revelationType: 'Makki' },
  { number: 110, name: 'An Nasr', arabicName: 'اَلنَّصْر', englishMeaning: 'Divine Support', versesCount: 3, revelationType: 'Madani' },
  { number: 111, name: 'Al Lahab', arabicName: 'اَللَّھَب', englishMeaning: 'The Palm Fiber', versesCount: 5, revelationType: 'Makki' },
  { number: 112, name: 'Al Ikhlas', arabicName: 'اَلْاِخْلَاص', englishMeaning: 'Sincerity', versesCount: 4, revelationType: 'Makki' },
  { number: 113, name: 'Al Falaq', arabicName: 'اَلْفَلَق', englishMeaning: 'The Daybreak', versesCount: 5, revelationType: 'Makki' },
  { number: 114, name: 'An Nas', arabicName: 'اَلنَّاس', englishMeaning: 'Mankind', versesCount: 6, revelationType: 'Makki' },
]

export function getSurahMeta(number: number): SurahMeta | undefined {
  return SURAHS.find((s) => s.number === number)
}

export const TOTAL_AYAHS = SURAHS.reduce((sum, s) => sum + s.versesCount, 0)
